### ISSUE TITLE
CRAN checklist

### ISSUE THREAD

**Issue by RamiKrispin** [Covid19R/coronavirus#4]
- [ ] Update the readme

- [ ] Update the package site

- [ ] Update the package vignette

- [ ] Update the package news
